// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using models;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20220330115638_adicionando tabela vendedor")]
    partial class adicionandotabelavendedor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("WebApplication2.Models.Clientes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<string>("dataNascimento")
                        .HasColumnType("text");

                    b.Property<string>("nomeCliente")
                        .HasColumnType("text");

                    b.Property<string>("sobrenomeCliente")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApplication2.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vendedor");
                });

            modelBuilder.Entity("models.Produtos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nomeProduto")
                        .HasColumnType("text");

                    b.Property<int>("quantidadeProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("valorProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("models.Vendas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("nomeCliente")
                        .HasColumnType("text");

                    b.Property<string>("nomeProduto")
                        .HasColumnType("text");

                    b.Property<int>("quantidadeComprada")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
